# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e1639d91290c46f3a4bc695dc5e2caaf7573da1f5202034e70d0163cf8ec7bd3838ea86362cd8a6fb98430ade513b92db5fe0ed6091ad884a3f47a2cb13d0d

test:
  secret_key_base: 2688680e011244a89924252f17b145cd4adcbe804a0447652510a5434bc8aa57102221ddefa3b8e1884c8de536006f40c05985976e61df2220b61a75a757ab94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
